#!/usr/bin/python3
"""RSA Factorization Challenge"""
from sys import argv
from math import isqrt

def find_prime_factors(num):
    """Find prime factors of a number"""
    for i in range(2, isqrt(num) + 1):
        if num % i == 0:
            if all(i % j != 0 for j in range(2, isqrt(i) + 1)):
                factor = num // i
                if all(factor % j != 0 for j in range(2, isqrt(factor) + 1)):
                    return factor, i
    return num, 1

def factorize_file(filename):
    """Factorize numbers from a file"""
    with open(filename) as f:
        for line in f:
            num = int(line.strip())
            p, q = find_prime_factors(num)
            print(f"{num}={p}*{q}")

if __name__ == "__main__":
    if len(argv) != 2:
        print(f"Usage: {argv[0]} <file>")
        exit(1)
    factorize_file(argv[1])
